import { Header } from "@/components/layout/Header";
import { UserProvider } from "@/context/UserContext/UserContext";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "../styles/globals.css";
import "../styles/variables.css";
import { AppProvider } from "@/context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="grow">
          <AppProvider>
            <Header />
            <main className="mx-auto max-w-7xl py-10 px-3 h-full">
              {children}
            </main>
          </AppProvider>
        </div>
      </body>
    </html>
  );
}
