FROM node:20-alpine AS dev

WORKDIR /app
COPY ./package*.json ./

COPY ./frontend/package*.json ./frontend/

RUN npm install --prefix ./frontend

COPY ./frontend ./frontend/

EXPOSE 3000

CMD ["npm", "run", "dev:frontend"]

# build
# docker build -f docker/Dockerfile.dev . -t ddr

# run
# docker run -p 3000:3000 ddr